version: '3.4'

services:
  countrycurrency.crawler.webapi:
    image: ${DOCKER_REGISTRY-}countrycurrencycrawlerwebapi
    build:
      context: .
      dockerfile: CountryCurrency.Crawler.WebApi/Dockerfile
    ports:
      - "5000:5000"

  crawler.utils.webapi:
    image: ${DOCKER_REGISTRY-}crawlerutilswebapi
    build:
      context: .
      dockerfile: Extension/Crawler.Utils.WebApi/Dockerfile
    ports:
      - "5001:5001"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: netccc
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: netccc
    depends_on:
      - mongo

